export default [ 
    { from: 'A', to: 'B' },
    { from: 'B', to: 'C' },
    { from: 'C', to: 'D' },
    { from: 'D', to: 'E' },
    { from: 'E', to: 'G' },
    { from: 'G', to: 'H' },
    { from: 'E', to: 'F' },
    { from: 'H', to: 'F' },
    { from: 'F', to: 'J' },
    { from: 'H', to: 'I' },
    { from: 'J', to: 'K' },
    { from: 'K', to: 'L' },
    { from: 'B', to: 'L' },
    { from: 'L', to: 'M' },
    { from: 'M', to: 'N' },
    // Add all connections for two-way edges
    { from: 'B', to: 'A' },
    { from: 'C', to: 'B' },
    { from: 'D', to: 'C' },
    { from: 'G', to: 'E' },
    { from: 'H', to: 'G' },
    { from: 'F', to: 'E' },
    { from: 'F', to: 'H' },
    { from: 'J', to: 'F' },
    { from: 'I', to: 'H' },
    { from: 'K', to: 'J' },
    { from: 'L', to: 'K' },
    { from: 'L', to: 'B' },
    { from: 'M', to: 'L' },
    { from: 'N', to: 'M' },
]